Import('rtconfig')
from building import *
src = Split("""

rt-thread/ethoc.c
rt-thread/uipif.c

uip/psock.c
uip/uip_arp.c
uip/uip.c
uip/uip-fw.c
uip/uiplib.c
uip/uip-neighbor.c
uip/uip-split.c
uip/uip_timer.c


apps/webserver/httpd.c
apps/webserver/httpd-cgi.c
apps/webserver/httpd-fs.c
apps/webserver/http-strings.c

""")

path = [GetCurrentDir() + '/uip',
    GetCurrentDir() + '/rt-thread',
    GetCurrentDir() + '/apps/webserver',
    GetCurrentDir() + '/apps/webserver']

group = DefineGroup('uip', src, depend = ['RT_USING_UIP'], CPPPATH = path)

Return('group')

